### ISSUE TITLE
Imperfection: Zoom in on hover

### ISSUE THREAD

**Issue by alfiephillips** [alfiephillips/hiyield-challenges#1]
Location: [index.php](https://github.com/alfiephillips/hiyield-challenges/blob/master/hiyield_wp/wp-content/themes/hiyield_theme/index.php?plain=26)

I believe I need to change the class 'zoom-img' in [style.css](https://github.com/alfiephillips/hiyield-challenges/blob/master/hiyield_wp/wp-content/themes/hiyield_theme/style.css?plain=17) to not use a transition in order to stop the animation being applied to the entire object.

Thank you for your help!

**Comment by callumholloway** [comment]
You'll want to wrap a div around the image that has `overflow-hidden` on it, this will retain the scale/zoom in effect but hide the overflowing 👍
