### ISSUE TITLE
Imperfection: Text hover attribute not applied when hovering over A tag.

### ISSUE THREAD

**Issue by alfiephillips** [alfiephillips/hiyield-challenges#2]
Location: [index.php](https://github.com/alfiephillips/hiyield-challenges/blob/master/hiyield_wp/wp-content/themes/hiyield_theme/index.php?plain=33)

I'm trying to work out how to apply a transition to the text for a title in the blog post when the A tag has been placed on hover.

**Comment by callumholloway** [comment]
https://tailwindcss.com/docs/hover-focus-and-other-states check out `group-hover`! `group` on your parent element and then `group-hover:{whateveryouwant}` on the child

**Comment by alfiephillips** [comment]
Thanks for the insight. This feature seems like it can be extremely useful. I will add this to the solution.
