### ISSUE TITLE
Redundancy: HTML Preflight being applied manually as well as via Tailwindcss

### ISSUE THREAD

**Issue by ThePlayerSD** [alfiephillips/hiyield-challenges#4]
It seems that HTML Preflight, which is resetting default HTML styles, is being applied manually in [style.css](https://github.com/alfiephillips/hiyield-challenges/blob/master/hiyield_wp/wp-content/themes/hiyield_theme/style.css?plain=17).
This would have already been applied [via Tailwindcss](https://tailwindcss.com/docs/preflight).
It could be worth removing the HTML Preflight in favour of the one that comes with Tailwindcss?

**Comment by alfiephillips** [comment]
Thanks for this! I was unaware about the base styles that come with Tailwind. I will remove the HTML Preflight now.

**Comment by alfiephillips** [comment]
Is it common to use custom preflight styles? Perhaps avoiding the use of tailwind preflight as I saw an option in the tailwind configuration to disable it.

**Comment by ThePlayerSD** [comment]
It's common to use the Tailwindcss Preflight rules. It covers a little more than the custom preflight here and is maintained by Tailwindcss which takes the responsibility off ourselves. The background and font family can stay on a body or HTML level.

Just saw the commit you did! That looks good thank you. 

I'll close this one now as it has been resolved
